### ISSUE TITLE
Nag restart na naman po ngayon

### ISSUE THREAD

**Issue by cybermind2** [AdoPiSoft/Beta-Releases#1]
in between 1:00AM to 10:10AM, February 18,2022 nag restart na naman po using 5.1.2 beta 7

May time na yung user is hindi maka start ng tine.Already connected ang error. Need ko pang iistart dito sa dashboard manually
[system-report (6).txt](https://github.com/AdoPiSoft/Beta-Releases/files/8090802/system-report.6.txt)
.

**Comment by VinSheen** [comment]
Baka naman po sa Power Supply mo yan sir. Kasi nag update rin ako sa Beta-6 to Beta-7, I never experienced random restarts since yesterday. PLease see attached photo.

Machine type: OPI PC with VLAN22
version used: V5.1.2-beta 7
PSU: 12V 10A rated power supply

![image](https://user-images.githubusercontent.com/91281244/154557493-87a70ff3-df81-4bb3-ba3c-4089d9a41fc3.png)

**Comment by VinSheen** [comment]
![image](https://user-images.githubusercontent.com/91281244/154557579-8ba271cd-bb16-4412-ac4b-19065f815e53.png)

Never pa yan nag restart since last update to Beta 6

**Comment by alenteria** [comment]
Already fixed on latest beta release https://github.com/AdoPiSoft/Beta-Releases/releases/latest
