### ISSUE TITLE
v5.1.2-08302022 Sometimes license needs to be inputted again after reboot

### ISSUE THREAD

**Issue by shown19** [AdoPiSoft/Beta-Releases#79]
As the title says, may time na pag nagrerestart ako sa vendo, need ulit iinput yong license details. Please fix this kahit eto lang na issue for now kasi mas hassle siya pag wala ka sa bahay or remote connection is not working. Thank you.

**Comment by nelfox07** [comment]
Na experience ko din yan many times. Gumagamit kasi ako ng timer to turn off & on sa machine ko para ma-refresh every day. After mag on yong timer, deactivated na ang machine ko. Wla ng license & it needs to reboot the machine again pra bumalik yong license. And now sinubukan ko na rin ang v5.1.3beta1. Sana working well

**Comment by verniegithub** [comment]
I have experienced a lot of problems with my setup where reading of coin slot signal becomes a hit and miss and later only selected coins can have correct reading. With no other option left, I decided to have a fresh install using the same sd card, version 5.0.0 then upgraded to 5.1.2 which is same as v5.1.2-08302022 for orange pi image. All issues solved after setting all same settings I used as before. The previous setup were done with incremental upgrade that later on resulted to problems. Could this issue of license need to be added again as it was gone after a reboot be related to the same other issues I experienced? A clean install might help. So far my new setup have gone several reboots due to configuration changes but never have the issue on license yet.  I decided to have  fresh install as things becomes no more logical to me. I know my hardware and I do testing on different configurations and do incremental upgrades also.

**Comment by nelfox07** [comment]
@verniegithub ganyan dn ang ginawa ko. Fresh install from 5.0.0 then v5.1.2-08302022 via debian file pro ganun pa rin ang problema

**Comment by adonespitogo** [comment]
We are aware of this issue. If possible please test our latest beta releases and give us feed back. Thanks.

**Comment by adonespitogo** [comment]
The fix for this has already been merged and will be shipped in the next upcoming beta release. Thank you for patience.
